### ISSUE TITLE
MPM algorithm

### ISSUE THREAD

**Issue by kks32** [cb-geo/mpm3d-doc#1]
* Describe with flowchart the MPM algorithm and implementation details

**Comment by ezrayst** [comment]
@kks32, I think it would be helpful if you provide an example on how you want us to document this. For instance like format and style of writing. Thanks!

**Comment by kks32** [comment]
For reference see https://lem-doc.cb-geo.com/stiffness/stiffness.html

**Comment by ezrayst** [comment]
@kks32, could you help create the template? I am not sure whether we should use github or gitbook,

**Comment by ezrayst** [comment]
I am thinking of making the algorithm from the attached document, Box 5.1 and 5.2 (we are using USF right?)
[Nguyen - MPM basics and applications.pdf](https://github.com/cb-geo/mpm3d-doc/files/1271673/Nguyen.-.MPM.basics.and.applications.pdf)

I am not sure what is the best way to create figures.

**Comment by ezrayst** [comment]
@kks32, I really want to start working on the Algorithm. Do you want to make a list of do you want to make nice figures?

**Comment by kks32** [comment]
Don't worry about figures. @cw646 has figures. Could you write the algorithm based on the implementation.
